import type { Metadata } from 'next'
import '../globals.css'
import { ThemeProvider } from "../../components/theme-provider";

export const metadata: Metadata = {
  title: 'Threads -HOME',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      disableTransitionOnChange
    >{children}
    </ThemeProvider>
  )
}
